DISPLAY=:0 
XDG_RUNTIME_DIR=/run/user/0 
KCFG_GRAPHICS_FULLSCREEN=auto 
KIVY_GLES_LIMITS=1 
KCFG_INPUT_MOUSE='mouse,disable_on_activity' 
KCFG_KIVY_KEYBOARD_MODE='systemanddock'
WAYLAND_DISPLAY=/run/wayland-0

export DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR KCFG_GRAPHICS_FULLSCREEN KIVY_GLES_LIMITS KCFG_INPUT_MOUSE KCFG_KIVY_KEYBOARD_MODE
